# Generated by Django 5.2 on 2025-08-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcataloge',
            name='deault_cataloge',
            field=models.BooleanField(default=True),
        ),
    ]
