# Generated by Django 5.2 on 2025-10-12 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_clientcataloge_deault_cataloge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientcataloge',
            old_name='deault_cataloge',
            new_name='default_cataloge',
        ),
    ]
