# Generated by Django 5.2 on 2025-05-07 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_remove_clientbusiness_order_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='client_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientbusiness',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientcataloge',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='client_catalog', to=settings.AUTH_USER_MODEL),
        ),
    ]
