# Generated by Django 5.2 on 2025-05-07 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0004_alter_staffprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbusiness',
            name='sales_rep',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True, 'is_superuser': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_handled', to=settings.AUTH_USER_MODEL),
        ),
    ]
