# Generated by Django 5.2 on 2025-05-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0005_alter_clientbusiness_sales_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbusiness',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='buyers/images/cafe_logos/'),
        ),
        migrations.AlterField(
            model_name='clientcataloge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='buyers/images/client_images/'),
        ),
    ]
