# Generated by Django 5.2 on 2025-07-27 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuickBooksToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('realm_id', models.CharField(max_length=255)),
                ('expires_in', models.IntegerField()),
                ('x_refresh_token_expires_in', models.IntegerField()),
                ('last_refreshed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
