# Generated by Django 5.2 on 2025-05-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(default='s', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight_unit',
            field=models.CharField(default='g', max_length=20),
            preserve_default=False,
        ),
    ]
