# Generated by Django 5.2 on 2025-05-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_clientcatalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mass_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packer_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packer_length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packer_width',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_inventory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='units',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size_unit', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('packer_length', models.FloatField()),
                ('packer_width', models.FloatField()),
                ('packer_height', models.FloatField()),
                ('stock_inventory', models.PositiveIntegerField()),
                ('expiry', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='products.product')),
            ],
        ),
    ]
