# Generated by Django 5.2 on 2025-05-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productvariant_packer_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='packer_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='packer_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='packer_width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
