# Generated by Django 5.2 on 2025-05-07 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0005_alter_clientbusiness_sales_rep'),
        ('products', '0004_alter_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientCatalog',
            new_name='ProductCatalog',
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='catalog',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_catalog', to='buyers.clientcataloge'),
        ),
    ]
