# Generated by Django 5.2 on 2025-05-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productvariant_packer_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='logo',
        ),
    ]
