# Generated by Django 5.2 on 2025-10-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcatalog',
            name='product',
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='product',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
