# Generated by Django 5.2 on 2025-05-08 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0006_alter_clientbusiness_logo_alter_clientcataloge_image'),
        ('products', '0006_alter_brand_logo_alter_category_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/brands/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/categories/'),
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_catalog', to='buyers.clientcataloge'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/images/products/'),
        ),
    ]
