# Generated by Django 5.2 on 2025-10-12 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productcatalog_product_productcatalog_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcatalog',
            name='product',
        ),
        migrations.AddField(
            model_name='productcatalog',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
